# Generated by Django 5.2.1 on 2025-06-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="role",
            new_name="level",
        ),
        migrations.AlterField(
            model_name="agent",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
