# Generated by Django 5.2.1 on 2025-06-14 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_role_agent_level_alter_agent_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="agent",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default=django.utils.timezone.now,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="last_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
