# Generated by Django 5.2.1 on 2025-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_name_agent_first_name_agent_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("closed", "Closed"),
                    ("Unassigned", "Unassigned"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
